worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Upstreams
    upstream inventory_backend {
        least_conn;
        server 127.0.0.1:8000;
    }

    upstream payment_backend {
        least_conn;
        server 127.0.0.1:8001;
    }

    upstream auth_backend {
        least_conn;
        server 127.0.0.1:8080;
    }

    server {
        listen 80;

        location /inventory/ {
            proxy_pass http://inventory_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # Proxy for /payment/
        location /payment/ {
            proxy_pass http://payment_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy for /auth/
        location /auth/ {
            proxy_pass http://auth_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve frontend
        location / {
            root   ../html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html =404;
        }
          
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   ../html;
        }
    }
}
